version: "3.8"

services:
  pg:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true

networks:
  reminders_net:
  
volumes:
  data: